tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"
tap "homebrew/services"

brew "awscli"
brew "bat"
brew "coreutils"
brew "fzf"
brew "git"
brew "glib"
brew "gnu-sed"
brew "graphviz"
brew "harfbuzz"
brew "jq"
brew "lua-language-server"
brew "neovim"
brew "postgresql", restart_service: true
brew "pyenv"
brew "ripgrep"
brew "shellcheck"
brew "tmux"
cask "rectangle"
cask "font-hack-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "ghostty" 